@startuml
set namespaceSeparator ::

class "learning_hub::objects::addEventPopup.dart::AddEvent" {
  +CustomUser user
  +AddEventState createState()
}

"learning_hub::objects::addEventPopup.dart::AddEvent" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::addEventPopup.dart::AddEventState" {
  -GlobalKey<FormState> _formKey
  +List<bool> days
  +dynamic title
  +dynamic location
  +dynamic teacher
  +dynamic start
  +dynamic end
  +bool boxValueA
  +bool boxValueB
  +bool daysFilled
  +bool weeksFilled
  +bool timesValid
  +Widget build()
}

class "learning_hub::objects::addPersonalTask.dart::AddPersonalTask" {
  +CustomUser user
  +AddPersonalTaskState createState()
}

"learning_hub::objects::addPersonalTask.dart::AddPersonalTask" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::addPersonalTask.dart::AddPersonalTaskState" {
  -GlobalKey<FormState> _formKey
  +dynamic title
  +dynamic description
  +dynamic subject
  +DateTime dueDate
  +bool dueDateSet
  +Widget build()
}

class "learning_hub::objects::assignment.dart::Assignment" {
  +String url
  +String platform
  +String courseId
  +String courseName
  +String submissionId
  +String title
  +String description
  +String id
  +String status
  +String type
  +DateTime creationTime
  +DateTime updateTime
  +String creatorId
  +DateTime dueDate
  +List<Attachment> attachments
  +List<Attachment> submissionAttachments
  +Question question
  +int points
  +String state
  +bool isLate
  +int grade
  +String answer
}

"learning_hub::objects::assignment.dart::Assignment" o-- "learning_hub::objects::question.dart::Question"

class "learning_hub::objects::assignments_list_view.dart::AssignmentsListView" {
  +List assignments
  +CustomUser user
  +dynamic courseName
  +dynamic courseId
  +bool timetable
  +AssignmentsListViewState createState()
}

"learning_hub::objects::assignments_list_view.dart::AssignmentsListView" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::assignments_list_view.dart::_CustomListRow" {
  +Assignment assignment
  +CustomUser user
  +_CustomListRowState createState()
}

"learning_hub::objects::assignments_list_view.dart::_CustomListRow" o-- "learning_hub::objects::assignment.dart::Assignment"
"learning_hub::objects::assignments_list_view.dart::_CustomListRow" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::assignments_list_view.dart::_CustomListRowState" {
  +Widget build()
  {static} -void _pushAssignmentPage()
}

class "learning_hub::objects::attachment.dart::Attachment" {
  +String title
  +String link
  +String id
  +String thumbnail
  +String type
}

class "learning_hub::objects::attachments_list_view.dart::AttachmentsListView" {
  +List<Attachment> attachments
  +dynamic description
  +AttachmentsListViewState createState()
}

class "learning_hub::objects::attachments_list_view.dart::_FirstTile" {
  +dynamic description
  +bool attachments
  +_FirstTileState createState()
}

class "learning_hub::objects::attachments_list_view.dart::_CustomListRow" {
  +Attachment attachment
  +_CustomListRowState createState()
}

"learning_hub::objects::attachments_list_view.dart::_CustomListRow" o-- "learning_hub::objects::attachment.dart::Attachment"

class "learning_hub::objects::course.dart::Course" {
  +String name
  +String description
  +String platform
  +String id
  +String status
}

class "learning_hub::objects::courses_list_view.dart::CoursesListView" {
  +List<Course> courses
  +CustomUser user
  +CoursesListViewState createState()
}

"learning_hub::objects::courses_list_view.dart::CoursesListView" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::courses_list_view.dart::_CustomListRow" {
  +Course course
  +CustomUser user
  +_CustomListRowState createState()
}

"learning_hub::objects::courses_list_view.dart::_CustomListRow" o-- "learning_hub::objects::course.dart::Course"
"learning_hub::objects::courses_list_view.dart::_CustomListRow" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::customUser.dart::CustomUser" {
  +User firebaseUser
  +Map<String, dynamic> authHeaders
}

class "learning_hub::objects::custom_app_bar.dart::CustomAppBar" {
  +dynamic title
  +bool reload
  +Size preferredSize
  +CustomAppBarState createState()
}

class "learning_hub::objects::custom_navigation_bar.dart::CustomNavigationBar" {
  +dynamic name
  +CustomUser user
  +int index
  +CustomNavigationBarState createState()
}

"learning_hub::objects::custom_navigation_bar.dart::CustomNavigationBar" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::custom_navigation_bar.dart::CustomNavigationBarState" {
  {static} -void _pushAccountPage()
  {static} -void _pushCoursesPage()
  {static} -void _pushTannoyPage()
  {static} -void _pushTimetablePage()
  +Widget build()
}

class "learning_hub::objects::event.dart::Event" {
  +String id
  +String classSet
  +String location
  +String name
  +String platform
  +String teacher
  +List<List<String>> times
  +int compareTo()
}

class "learning_hub::objects::events_list_view.dart::EventsListView" {
  +List<Event> events
  +CustomUser user
  +EventsListViewState createState()
}

"learning_hub::objects::events_list_view.dart::EventsListView" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::events_list_view.dart::_CustomListRow" {
  +Event event
  +CustomUser user
  +_CustomListRowState createState()
}

"learning_hub::objects::events_list_view.dart::_CustomListRow" o-- "learning_hub::objects::event.dart::Event"
"learning_hub::objects::events_list_view.dart::_CustomListRow" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::notice.dart::Notice" {
  +String title
  +String body
  +String author
}

class "learning_hub::objects::offlineScaffold.dart::OfflineScaffold" {
  +OfflineScaffoldState createState()
}

class "learning_hub::objects::question.dart::Question" {
  +String type
  +List<String> options
}

class "learning_hub::objects::showEventPopup.dart::ShowEvent" {
  +CustomUser user
  +dynamic id
  +ShowEventState createState()
}

"learning_hub::objects::showEventPopup.dart::ShowEvent" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::showEventPopup.dart::ShowEventState" {
  +bool showConfirm
  +Widget build()
}

class "learning_hub::objects::student_submissions.dart::StudentSubmissions" {
  +Assignment assignment
  +CustomUser user
  +StudentSubmissionsState createState()
}

"learning_hub::objects::student_submissions.dart::StudentSubmissions" o-- "learning_hub::objects::assignment.dart::Assignment"
"learning_hub::objects::student_submissions.dart::StudentSubmissions" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::objects::student_submissions.dart::StudentSubmissionsState" {
  +dynamic answer
  +Widget build()
}

class "learning_hub::objects::tannoy_list_view.dart::TannoysListView" {
  +List<Notice> notices
  +TannoysListViewState createState()
}

class "learning_hub::objects::tannoy_list_view.dart::_CustomListRow" {
  +Notice notice
  +_CustomListRowState createState()
}

"learning_hub::objects::tannoy_list_view.dart::_CustomListRow" o-- "learning_hub::objects::notice.dart::Notice"

class "learning_hub::pages::account_page.dart::AccountPage" {
  +GoogleSignInAccount account
  +dynamic name
  +CustomUser user
  +bool toSignOut
  +AccountPageState createState()
}

"learning_hub::pages::account_page.dart::AccountPage" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::account_page.dart::_CustomScaffold" {
  +dynamic name
  +CustomUser user
  +_CustomScaffoldState createState()
}

"learning_hub::pages::account_page.dart::_CustomScaffold" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::account_page.dart::_CustomScaffoldState" {
  +bool showEventConfirm
  +bool showTasksConfirm
  +bool showAllConfirm
  +Widget build()
  {static} -void _pushSignOut()
}

class "learning_hub::pages::assignments_page.dart::AssignmentsPage" {
  +GoogleSignInAccount account
  +dynamic name
  +dynamic id
  +dynamic course
  +CustomUser user
  +AssignmentsPageState createState()
}

"learning_hub::pages::assignments_page.dart::AssignmentsPage" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::assignments_page.dart::_CustomScaffold" {
  +dynamic name
  +CustomUser user
  +dynamic course
  +dynamic id
  +_CustomScaffoldState createState()
}

"learning_hub::pages::assignments_page.dart::_CustomScaffold" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::assignment_page.dart::AssignmentPage" {
  +GoogleSignInAccount account
  +dynamic name
  +Assignment assignment
  +CustomUser user
  +AssignmentPageState createState()
}

"learning_hub::pages::assignment_page.dart::AssignmentPage" o-- "learning_hub::objects::assignment.dart::Assignment"
"learning_hub::pages::assignment_page.dart::AssignmentPage" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::assignment_page.dart::_CustomScaffold" {
  +dynamic name
  +CustomUser user
  +Assignment assignment
  +_CustomScaffoldState createState()
}

"learning_hub::pages::assignment_page.dart::_CustomScaffold" o-- "learning_hub::objects::customUser.dart::CustomUser"
"learning_hub::pages::assignment_page.dart::_CustomScaffold" o-- "learning_hub::objects::assignment.dart::Assignment"

class "learning_hub::pages::courses_page.dart::CoursesPage" {
  +GoogleSignInAccount account
  +dynamic name
  +CustomUser user
  +CoursesPageState createState()
}

"learning_hub::pages::courses_page.dart::CoursesPage" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::courses_page.dart::_CustomScaffold" {
  +dynamic name
  +CustomUser user
  +_CustomScaffoldState createState()
}

"learning_hub::pages::courses_page.dart::_CustomScaffold" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::dashboard_web_view.dart::DashboardWebView" {
  +CustomUser user
  +dynamic url
  +bool events
  +DashboardWebViewState createState()
}

"learning_hub::pages::dashboard_web_view.dart::DashboardWebView" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::dashboard_web_view.dart::_CustomBody" {
  +dynamic url
  +CustomUser user
  +bool events
  +_CustomBodyState createState()
}

"learning_hub::pages::dashboard_web_view.dart::_CustomBody" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::dashboard_web_view.dart::_CustomBodyState" {
  +Widget build()
  {static} -void _pushTimetablePage()
}

class "learning_hub::pages::portal_web_view.dart::PortalWebView" {
  +CustomUser user
  +dynamic url
  +PortalWebViewState createState()
}

"learning_hub::pages::portal_web_view.dart::PortalWebView" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::portal_web_view.dart::_CustomBody" {
  +dynamic url
  +CustomUser user
  +_CustomBodyState createState()
}

"learning_hub::pages::portal_web_view.dart::_CustomBody" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::portal_web_view.dart::_CustomBodyState" {
  +Widget build()
  {static} -void _pushTannoyPage()
}

class "learning_hub::pages::tannoy_page.dart::TannoyPage" {
  +dynamic name
  +CustomUser user
  +TannoyPageState createState()
}

"learning_hub::pages::tannoy_page.dart::TannoyPage" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::tannoy_page.dart::_CustomScaffold" {
  +CustomUser user
  +dynamic name
  +_CustomScaffoldState createState()
}

"learning_hub::pages::tannoy_page.dart::_CustomScaffold" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::tannoy_page.dart::_CustomScaffoldState" {
  +Widget build()
  {static} -void _pushTannoyPage()
}

class "learning_hub::pages::timetable_page.dart::TimetablePage" {
  +dynamic name
  +CustomUser user
  +TimetablePageState createState()
}

"learning_hub::pages::timetable_page.dart::TimetablePage" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::timetable_page.dart::_CustomScaffold" {
  +CustomUser user
  +dynamic name
  +_CustomScaffoldState createState()
}

"learning_hub::pages::timetable_page.dart::_CustomScaffold" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::timetable_page.dart::_MainPage" {
  +CustomUser user
  +dynamic name
  +DateTime time
  +dynamic week
  +_MainPageState createState()
}

"learning_hub::pages::timetable_page.dart::_MainPage" o-- "learning_hub::objects::customUser.dart::CustomUser"

class "learning_hub::pages::timetable_page.dart::_MainPageState" {
  +DateTime time
  +dynamic week
  +Widget build()
}

@enduml